# Generated by Django 4.0.4 on 2022-06-10 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_productov2_producto_delete_core_producto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='idProd',
            field=models.IntegerField(max_length=25, primary_key=True, serialize=False, verbose_name='codigo de barra'),
        ),
    ]
