# Generated by Django 4.0.4 on 2022-06-10 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_producto_idprod'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='idProd',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='codigo de barra'),
        ),
    ]
