# Generated by Django 4.0.4 on 2022-06-10 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('iid', models.IntegerField(primary_key=True, serialize=False, verbose_name='codigo de barra')),
                ('nombre', models.CharField(max_length=60)),
                ('precio', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('correo', models.EmailField(max_length=254, verbose_name='Correo')),
            ],
        ),
    ]
