# Generated by Django 4.0.4 on 2022-06-10 04:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_productov2'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Producto',
            new_name='core_producto',
        ),
        migrations.RenameField(
            model_name='core_producto',
            old_name='iid',
            new_name='idProd',
        ),
    ]
