# Generated by Django 4.0.4 on 2022-06-10 04:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_producto_core_producto_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Productov2',
            new_name='Producto',
        ),
        migrations.DeleteModel(
            name='core_producto',
        ),
        migrations.RenameField(
            model_name='producto',
            old_name='iid',
            new_name='idProd',
        ),
    ]
